<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HR7OA0S" name="tests.TestExtInvSupPortalDef" tests="1" failures="0" timestamp="27 Jan 2016 20:06:40 GMT" time="0.001" errors="1">
  <testcase name="test_1339" time="0.001" classname="tests.TestExtInvSupPortalDef">
    <error type="java.lang.AssertionError" message="&lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;&lt;env:Header&gt;&lt;wsa:MessageID&gt;urn:71D1EA80C53111E5AF18834814C4341D&lt;/wsa:MessageID&gt;&lt;wsa:ReplyTo&gt;&lt;wsa:Address&gt;http://www.w3.org/2005/08/addressing/anonymous&lt;/wsa:Address&gt;&lt;wsa:ReferenceParameters&gt;&lt;instra:tracking.compositeInstanceCreatedTime xmlns:instra=&quot;http://xmlns.oracle.com/sca/tracking/1.0&quot;&gt;2016-01-27T20:06:21.855Z&lt;/instra:tracking.compositeInstanceCreatedTime&gt;&lt;/wsa:ReferenceParameters&gt;&lt;/wsa:ReplyTo&gt;&lt;wsa:FaultTo&gt;&lt;wsa:Address&gt;http://www.w3.org/2005/08/addressing/anonymous&lt;/wsa:Address&gt;&lt;wsa:ReferenceParameters&gt;&lt;instra:tracking.compositeInstanceCreatedTime xmlns:instra=&quot;http://xmlns.oracle.com/sca/tracking/1.0&quot;&gt;2016-01-27T20:06:21.855Z&lt;/instra:tracking.compositeInstanceCreatedTime&gt;&lt;/wsa:ReferenceParameters&gt;&lt;/wsa:FaultTo&gt;&lt;/env:Header&gt;&lt;env:Body&gt;&lt;startResponse xmlns=&quot;http://xmlns.oracle.com/bpmn/bpmnProcess/SupplierPortalApprovalProcess&quot;&gt;&lt;ExternalInvoiceResponse xmlns=&quot;http://xmlns.oracle.com/bpm/bpmobject/PrePopInvoice/ExternalInvoiceResponse&quot;&gt;&lt;code&gt;0&lt;/code&gt;&lt;responseMessage&gt;Success&lt;/responseMessage&gt;&lt;/ExternalInvoiceResponse&gt;&lt;/startResponse&gt;&lt;/env:Body&gt;&lt;/env:Envelope&gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsa="http://www.w3.org/2005/08/addressing"><env:Header><wsa:MessageID>urn:71D1EA80C53111E5AF18834814C4341D</wsa:MessageID><wsa:ReplyTo><wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address><wsa:ReferenceParameters><instra:tracking.compositeInstanceCreatedTime xmlns:instra="http://xmlns.oracle.com/sca/tracking/1.0">2016-01-27T20:06:21.855Z</instra:tracking.compositeInstanceCreatedTime></wsa:ReferenceParameters></wsa:ReplyTo><wsa:FaultTo><wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address><wsa:ReferenceParameters><instra:tracking.compositeInstanceCreatedTime xmlns:instra="http://xmlns.oracle.com/sca/tracking/1.0">2016-01-27T20:06:21.855Z</instra:tracking.compositeInstanceCreatedTime></wsa:ReferenceParameters></wsa:FaultTo></env:Header><env:Body><startResponse xmlns="http://xmlns.oracle.com/bpmn/bpmnProcess/SupplierPortalApprovalProcess"><ExternalInvoiceResponse xmlns="http://xmlns.oracle.com/bpm/bpmobject/PrePopInvoice/ExternalInvoiceResponse"><code>0</code><responseMessage>Success</responseMessage></ExternalInvoiceResponse></startResponse></env:Body></env:Envelope> expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at tests.TestExtInvSupPortalDef.setup(TestExtInvSupPortalDef.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- test_1339 -->
</testsuite> <!-- tests.TestExtInvSupPortalDef -->
